
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class AuditLog
{

    public int AuditID { get; set; }

    public System.DateTime EventDate { get; set; }

    public string UserLogin { get; set; }

    public Nullable<int> EmployeeID { get; set; }

    public Nullable<int> UserID { get; set; }

    public string ActionType { get; set; }

    public string EntityType { get; set; }

    public string EntityID { get; set; }

    public Nullable<int> ProductID { get; set; }

    public Nullable<int> SaleID { get; set; }

    public string ReportName { get; set; }

    public string ExportFormat { get; set; }

    public string Details { get; set; }

    public string Metadata { get; set; }



    public virtual Employees Employees { get; set; }

    public virtual Products Products { get; set; }

    public virtual Sales Sales { get; set; }

    public virtual Users Users { get; set; }

}

}
