
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Categories
{

    public Categories()
    {

        this.Categories1 = new HashSet<Categories>();

        this.Products = new HashSet<Products>();

    }


    public int CategoryID { get; set; }

    public string CategoryName { get; set; }

    public Nullable<int> ParentCategoryID { get; set; }



    public virtual ICollection<Categories> Categories1 { get; set; }

    public virtual Categories Categories2 { get; set; }

    public virtual ICollection<Products> Products { get; set; }

}

}
