
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class DefectiveProducts
{

    public int DefectiveID { get; set; }

    public int ProductID { get; set; }

    public Nullable<int> SaleID { get; set; }

    public int Quantity { get; set; }

    public string Reason { get; set; }

    public Nullable<System.DateTime> ReturnDate { get; set; }

    public Nullable<int> EmployeeID { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }



    public virtual Products Products { get; set; }

    public virtual Sales Sales { get; set; }

}

}
