
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Employees
{

    public Employees()
    {

        this.InventoryActs = new HashSet<InventoryActs>();

        this.Invoices = new HashSet<Invoices>();

        this.ProductMovementHistory = new HashSet<ProductMovementHistory>();

        this.Salaries = new HashSet<Salaries>();

        this.Sales = new HashSet<Sales>();

        this.Shifts = new HashSet<Shifts>();

        this.Shifts1 = new HashSet<Shifts>();

        this.Users = new HashSet<Users>();

        this.AuditLog = new HashSet<AuditLog>();

        this.Torg12Documents = new HashSet<Torg12Documents>();

    }


    public int EmployeeID { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public int PositionID { get; set; }

    public System.DateTime HireDate { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string PassportData { get; set; }

    public string INN { get; set; }

    public bool IsActive { get; set; }

    public string PhotoPath { get; set; }

    public byte[] PhotoData { get; set; }



    public virtual Positions Positions { get; set; }

    public virtual ICollection<InventoryActs> InventoryActs { get; set; }

    public virtual ICollection<Invoices> Invoices { get; set; }

    public virtual ICollection<ProductMovementHistory> ProductMovementHistory { get; set; }

    public virtual ICollection<Salaries> Salaries { get; set; }

    public virtual ICollection<Sales> Sales { get; set; }

    public virtual ICollection<Shifts> Shifts { get; set; }

    public virtual ICollection<Shifts> Shifts1 { get; set; }

    public virtual ICollection<Users> Users { get; set; }

    public virtual ICollection<AuditLog> AuditLog { get; set; }

    public virtual ICollection<Torg12Documents> Torg12Documents { get; set; }

}

}
