
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class InventoryDetails
{

    public int InventoryDetailID { get; set; }

    public int InventoryID { get; set; }

    public int ProductID { get; set; }

    public Nullable<int> ZoneID { get; set; }

    public int ExpectedQuantity { get; set; }

    public int ActualQuantity { get; set; }

    public Nullable<int> Discrepancy { get; set; }

    public string Notes { get; set; }



    public virtual InventoryActs InventoryActs { get; set; }

    public virtual Products Products { get; set; }

    public virtual WarehouseZones WarehouseZones { get; set; }

}

}
