
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class InventoryActs
{

    public InventoryActs()
    {

        this.InventoryDetails = new HashSet<InventoryDetails>();

    }


    public int InventoryID { get; set; }

    public System.DateTime InventoryDate { get; set; }

    public string Description { get; set; }

    public int PerformedBy { get; set; }

    public Nullable<int> ZoneID { get; set; }

    public string Status { get; set; }



    public virtual Employees Employees { get; set; }

    public virtual ICollection<InventoryDetails> InventoryDetails { get; set; }

    public virtual WarehouseZones WarehouseZones { get; set; }

}

}
