
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Invoices
{

    public Invoices()
    {

        this.InvoiceItems = new HashSet<InvoiceItems>();

    }


    public int InvoiceID { get; set; }

    public int SupplierID { get; set; }

    public string InvoiceNumber { get; set; }

    public System.DateTime InvoiceDate { get; set; }

    public System.DateTime ExpectedDeliveryDate { get; set; }

    public Nullable<System.DateTime> ActualDeliveryDate { get; set; }

    public int ShiftID { get; set; }

    public string Status { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string Notes { get; set; }



    public virtual Employees Employees { get; set; }

    public virtual ICollection<InvoiceItems> InvoiceItems { get; set; }

    public virtual Shifts Shifts { get; set; }

    public virtual Suppliers Suppliers { get; set; }

}

}
