
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class InvoiceItems
{

    public int InvoiceItemID { get; set; }

    public int InvoiceID { get; set; }

    public int ProductID { get; set; }

    public int ExpectedQuantity { get; set; }

    public Nullable<int> ReceivedQuantity { get; set; }

    public decimal UnitPrice { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }

    public string DiscrepancyReason { get; set; }



    public virtual Invoices Invoices { get; set; }

    public virtual Products Products { get; set; }

}

}
