

//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using DiplomMurtazin.Core;


public partial class KPMurtazinEntities : DbContext
{
    public KPMurtazinEntities()
        : base(ConnectionManager.BuildEntityConnectionString())
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Categories> Categories { get; set; }

    public DbSet<Employees> Employees { get; set; }

    public DbSet<InventoryActs> InventoryActs { get; set; }

    public DbSet<InventoryDetails> InventoryDetails { get; set; }

    public DbSet<InvoiceItems> InvoiceItems { get; set; }

    public DbSet<Invoices> Invoices { get; set; }

    public DbSet<Positions> Positions { get; set; }

    public DbSet<ProductMovementHistory> ProductMovementHistory { get; set; }

    public DbSet<Products> Products { get; set; }

    public DbSet<Salaries> Salaries { get; set; }

    public DbSet<SaleItems> SaleItems { get; set; }

    public DbSet<Sales> Sales { get; set; }

    public DbSet<Shifts> Shifts { get; set; }

    public DbSet<StockBalances> StockBalances { get; set; }

    public DbSet<Suppliers> Suppliers { get; set; }

    public DbSet<Users> Users { get; set; }

    public DbSet<WarehouseZones> WarehouseZones { get; set; }

    public DbSet<v_PopularProducts> v_PopularProducts { get; set; }

    public DbSet<UserViews> UserViews { get; set; }

    public DbSet<AuditLog> AuditLog { get; set; }

    public DbSet<Torg12Documents> Torg12Documents { get; set; }

    public DbSet<Torg12ImportMissingItems> Torg12ImportMissingItems { get; set; }

    public DbSet<Torg12Items> Torg12Items { get; set; }

}

}

