
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class ProductPriceHistory
{

    public int PriceHistoryID { get; set; }

    public int ProductID { get; set; }

    public decimal OldPrice { get; set; }

    public decimal NewPrice { get; set; }

    public System.DateTime ChangedAt { get; set; }

    public Nullable<int> ChangedByEmployeeID { get; set; }

    public string Source { get; set; }



    public virtual Products Products { get; set; }

}

}
