
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class ProductReturns
{

    public int ReturnID { get; set; }

    public int UnitID { get; set; }

    public int ProductID { get; set; }

    public Nullable<int> SaleID { get; set; }

    public Nullable<int> SaleItemID { get; set; }

    public System.DateTime ReturnDate { get; set; }

    public string ReturnReason { get; set; }

    public bool IsWarrantyCase { get; set; }

    public decimal RefundAmount { get; set; }

    public Nullable<int> ProcessedByEmployeeID { get; set; }



    public virtual Products Products { get; set; }

    public virtual ProductUnits ProductUnits { get; set; }

}

}
