
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class ProductUnits
{

    public ProductUnits()
    {

        this.ProductReturns = new HashSet<ProductReturns>();

    }


    public int UnitID { get; set; }

    public int ProductID { get; set; }

    public string SerialNumber { get; set; }

    public System.DateTime ReceivedDate { get; set; }

    public Nullable<System.DateTime> SoldDate { get; set; }

    public Nullable<int> SaleID { get; set; }

    public Nullable<int> SaleItemID { get; set; }

    public Nullable<System.DateTime> ReturnEndDate { get; set; }

    public Nullable<System.DateTime> WarrantyEndDate { get; set; }

    public string Status { get; set; }

    public Nullable<int> ReturnDocumentID { get; set; }

    public System.DateTime LastUpdated { get; set; }



    public virtual ICollection<ProductReturns> ProductReturns { get; set; }

    public virtual Products Products { get; set; }

    public virtual SaleItems SaleItems { get; set; }

    public virtual Sales Sales { get; set; }

}

}
