
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class ProductMovementHistory
{

    public int MovementID { get; set; }

    public int ProductID { get; set; }

    public string MovementType { get; set; }

    public int Quantity { get; set; }

    public Nullable<int> SourceDocumentID { get; set; }

    public string SourceDocumentType { get; set; }

    public System.DateTime MovementDate { get; set; }

    public Nullable<int> ZoneID { get; set; }

    public Nullable<int> EmployeeID { get; set; }



    public virtual Employees Employees { get; set; }

    public virtual Products Products { get; set; }

    public virtual WarehouseZones WarehouseZones { get; set; }

}

}
