
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Windows.Media.Imaging;

    public partial class Products
    {

        public Products()
        {

            this.InventoryDetails = new HashSet<InventoryDetails>();

            this.InvoiceItems = new HashSet<InvoiceItems>();

            this.ProductMovementHistory = new HashSet<ProductMovementHistory>();

            this.SaleItems = new HashSet<SaleItems>();

            this.StockBalances = new HashSet<StockBalances>();

            this.AuditLog = new HashSet<AuditLog>();

            this.Torg12ImportMissingItems = new HashSet<Torg12ImportMissingItems>();

            this.Torg12Items = new HashSet<Torg12Items>();

        }


        public int ProductID { get; set; }

        public string ProductName { get; set; }

        public int CategoryID { get; set; }

        public string Barcode { get; set; }

        public string Manufacturer { get; set; }

        public string Model { get; set; }

        public decimal UnitPrice { get; set; }

        public string PhotoPath { get; set; }
        public byte[] PhotoData { get; set; }
        public Nullable<int> WarrantyMonths { get; set; }

        public Nullable<int> MinStockLevel { get; set; }

        public string Description { get; set; }



        public virtual Categories Categories { get; set; }

        public virtual ICollection<InventoryDetails> InventoryDetails { get; set; }

        public virtual ICollection<InvoiceItems> InvoiceItems { get; set; }

        public virtual ICollection<ProductMovementHistory> ProductMovementHistory { get; set; }

        public virtual ICollection<SaleItems> SaleItems { get; set; }

        public virtual ICollection<StockBalances> StockBalances { get; set; }

        public virtual ICollection<AuditLog> AuditLog { get; set; }

        public virtual ICollection<Torg12ImportMissingItems> Torg12ImportMissingItems { get; set; }

        public virtual ICollection<Torg12Items> Torg12Items { get; set; }
        private int _stockQuantity;

        public int StockQuantity
        {
            get => _stockQuantity;
            set
            {
                _stockQuantity = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(StockQuantity)));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        public BitmapImage Photo
        {
            get
            {
                if (string.IsNullOrEmpty(PhotoPath))
                    return null;

                var image = new BitmapImage();
                image.BeginInit();
                image.UriSource = new Uri(PhotoPath, UriKind.RelativeOrAbsolute);
                image.CacheOption = BitmapCacheOption.OnLoad;
                image.EndInit();
                return image;
            }
        }
    }
}