
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Salaries
{

    public int SalaryID { get; set; }

    public int EmployeeID { get; set; }

    public System.DateTime PeriodStart { get; set; }

    public System.DateTime PeriodEnd { get; set; }

    public decimal BaseAmount { get; set; }

    public Nullable<decimal> Bonus { get; set; }

    public Nullable<decimal> Penalty { get; set; }

    public Nullable<decimal> TotalAmount { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public bool IsPaid { get; set; }



    public virtual Employees Employees { get; set; }

}

}
