
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Sales
{

    public Sales()
    {

        this.SaleItems = new HashSet<SaleItems>();

        this.AuditLog = new HashSet<AuditLog>();

    }


    public int SaleID { get; set; }

    public System.DateTime SaleDateTime { get; set; }

    public int ShiftID { get; set; }

    public int EmployeeID { get; set; }

    public decimal TotalAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string CashRegisterID { get; set; }

    public string FiscalDocumentNumber { get; set; }



    public virtual Employees Employees { get; set; }

    public virtual ICollection<SaleItems> SaleItems { get; set; }

    public virtual Shifts Shifts { get; set; }

    public virtual ICollection<AuditLog> AuditLog { get; set; }

}

}
