
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class SaleItems
{

    public int SaleItemID { get; set; }

    public int SaleID { get; set; }

    public int ProductID { get; set; }

    public string BarcodeScanned { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }



    public virtual Products Products { get; set; }

    public virtual Sales Sales { get; set; }

}

}
