
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Shifts
{

    public Shifts()
    {

        this.Invoices = new HashSet<Invoices>();

        this.Sales = new HashSet<Sales>();

    }


    public int ShiftID { get; set; }

    public int EmployeeID { get; set; }

    public System.DateTime ShiftStart { get; set; }

    public Nullable<System.DateTime> ShiftEnd { get; set; }

    public string CashRegisterID { get; set; }

    public Nullable<int> SupervisorID { get; set; }

    public string Notes { get; set; }



    public virtual Employees Employees { get; set; }

    public virtual Employees Employees1 { get; set; }

    public virtual ICollection<Invoices> Invoices { get; set; }

    public virtual ICollection<Sales> Sales { get; set; }

}

}
