
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class StockBalances
{

    public int StockID { get; set; }

    public int ProductID { get; set; }

    public int ZoneID { get; set; }

    public int Quantity { get; set; }

    public Nullable<System.DateTime> LastUpdated { get; set; }



    public virtual Products Products { get; set; }

    public virtual WarehouseZones WarehouseZones { get; set; }

}

}
