
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Suppliers
{

    public Suppliers()
    {

        this.Invoices = new HashSet<Invoices>();

    }


    public int SupplierID { get; set; }

    public string SupplierName { get; set; }

    public string ContactPerson { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string ContractNumber { get; set; }

    public Nullable<System.DateTime> ContractDate { get; set; }



    public virtual ICollection<Invoices> Invoices { get; set; }

}

}
