
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Torg12ImportMissingItems
{

    public int MissingID { get; set; }

    public int Torg12ID { get; set; }

    public string TempProductName { get; set; }

    public string TempBarcode { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public Nullable<int> CreatedProductID { get; set; }

    public string Status { get; set; }

    public System.DateTime CreatedDate { get; set; }



    public virtual Products Products { get; set; }

    public virtual Torg12Documents Torg12Documents { get; set; }

}

}
