
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Torg12Documents
{

    public Torg12Documents()
    {

        this.Torg12ImportMissingItems = new HashSet<Torg12ImportMissingItems>();

        this.Torg12Items = new HashSet<Torg12Items>();

    }


    public int Torg12ID { get; set; }

    public string DocumentNumber { get; set; }

    public System.DateTime DocumentDate { get; set; }

    public string ReceiverName { get; set; }

    public string ReceiverAddress { get; set; }

    public string ReceiverInn { get; set; }

    public string ReceiverKpp { get; set; }

    public string Basis { get; set; }

    public Nullable<int> CreatedByUserID { get; set; }

    public Nullable<int> CreatedByEmployeeID { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }



    public virtual Employees Employees { get; set; }

    public virtual Users Users { get; set; }

    public virtual ICollection<Torg12ImportMissingItems> Torg12ImportMissingItems { get; set; }

    public virtual ICollection<Torg12Items> Torg12Items { get; set; }

}

}
