
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class UserViews
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string TableName { get; set; }

    public string SelectedColumns { get; set; }

    public System.DateTime CreatedDate { get; set; }

}

}
