
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    public Users()
    {

        this.AuditLog = new HashSet<AuditLog>();

        this.Torg12Documents = new HashSet<Torg12Documents>();

    }


    public int UserID { get; set; }

    public int EmployeeID { get; set; }

    public string Login { get; set; }

    public string Role { get; set; }

    public Nullable<System.DateTime> LastLogin { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string Password { get; set; }

    public string PhotoPath { get; set; }



    public virtual Employees Employees { get; set; }

    public virtual ICollection<AuditLog> AuditLog { get; set; }

    public virtual ICollection<Torg12Documents> Torg12Documents { get; set; }

}

}
