
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class v_PopularProducts
{

    public int ProductID { get; set; }

    public string ProductName { get; set; }

    public string Barcode { get; set; }

    public string CategoryName { get; set; }

    public Nullable<int> TotalSold { get; set; }

    public Nullable<int> NumberOfReceipts { get; set; }

    public Nullable<long> RowID { get; set; }

}

}
