
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DiplomMurtazin
{

using System;
    using System.Collections.Generic;
    
public partial class WarehouseZones
{

    public WarehouseZones()
    {

        this.InventoryActs = new HashSet<InventoryActs>();

        this.InventoryDetails = new HashSet<InventoryDetails>();

        this.ProductMovementHistory = new HashSet<ProductMovementHistory>();

        this.StockBalances = new HashSet<StockBalances>();

    }


    public int ZoneID { get; set; }

    public string ZoneName { get; set; }

    public int Capacity { get; set; }

    public string Description { get; set; }



    public virtual ICollection<InventoryActs> InventoryActs { get; set; }

    public virtual ICollection<InventoryDetails> InventoryDetails { get; set; }

    public virtual ICollection<ProductMovementHistory> ProductMovementHistory { get; set; }

    public virtual ICollection<StockBalances> StockBalances { get; set; }

}

}
